/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuPrincipal
     */
    FRM_MantenimientoEstudiantes mantenimientoEstudiantes;
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    public FRM_MenuPrincipal() {
        initComponents();
        this.setLocation(500,300);
        controlador_FRM_MenuPrincipal= new Controlador_FRM_MenuPrincipal();
        mantenimientoEstudiantes= new FRM_MantenimientoEstudiantes();
        agregarEventos();
    }
    
    public void agregarEventos()
    {
     this.jm_Salir.addActionListener(controlador_FRM_MenuPrincipal);
     this.jm_Estudiantes.addActionListener(controlador_FRM_MenuPrincipal);
     this.jm_Cursos.addActionListener(controlador_FRM_MenuPrincipal);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JL_Fondo = new javax.swing.JLabel();
        jm_MenuPrincipal = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenuItem();
        Mantenimientos = new javax.swing.JMenu();
        jm_Estudiantes = new javax.swing.JMenuItem();
        jm_Cursos = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuInicio.png"))); // NOI18N

        Archivo.setText("Archivo");

        jm_Salir.setText("Salir");
        Archivo.add(jm_Salir);

        jm_MenuPrincipal.add(Archivo);

        Mantenimientos.setText("Mantenimientos");

        jm_Estudiantes.setText("Estudiantes");
        Mantenimientos.add(jm_Estudiantes);

        jm_Cursos.setText("Cursos");
        Mantenimientos.add(jm_Cursos);

        jm_MenuPrincipal.add(Mantenimientos);

        setJMenuBar(jm_MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_Fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_Fondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JLabel JL_Fondo;
    private javax.swing.JMenu Mantenimientos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jm_Cursos;
    private javax.swing.JMenuItem jm_Estudiantes;
    private javax.swing.JMenuBar jm_MenuPrincipal;
    private javax.swing.JMenuItem jm_Salir;
    // End of variables declaration//GEN-END:variables
}
