/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_Estudiantes;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoEstudiantes
     */
    Controlador_Estudiantes controlador_Estudiantes;
    public FRM_MantenimientoEstudiantes() {
        initComponents();
        setVisible(false);
        this.setLocation(500,200);
        controlador_Estudiantes=new Controlador_Estudiantes(this);
        gUI_Botones1.agregarEventosGUI(controlador_Estudiantes);
    }

    public String[] devolverInformacion()
    {
        return this.gUI_InformacionEstudiantes1.devolverInformacion();
    }
    
    public void blanquear()
    {
        gUI_InformacionEstudiantes1.blanquear();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        gUI_InformacionEstudiantes1 = new Vista.GUI_InformacionEstudiantes();
        gUI_Botones1 = new Vista.GUI_Botones();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(817, 320));
        getContentPane().setLayout(null);
        getContentPane().add(gUI_InformacionEstudiantes1);
        gUI_InformacionEstudiantes1.setBounds(10, 0, 280, 206);
        getContentPane().add(gUI_Botones1);
        gUI_Botones1.setBounds(20, -30, 816, 294);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/path4247.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 800));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 810, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
