/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_Cursos;
/**
 *
 * @author SOFIA ELIZONDO
 */
public class FRM_MantenimientoCusos extends javax.swing.JFrame {

    /**
     * Creates new form ManteniemientoCursos
     */
    Controlador_Cursos controlador_Cursos;
    public FRM_MantenimientoCusos() {
        initComponents();
        setVisible(false);
        this.setLocation(500,200);
        controlador_Cursos=new Controlador_Cursos(this);
        gUI_BotonesCursos1.agregarEventosGUI(controlador_Cursos);
       
    }
    
   public String devolverInformacion()
    {
        return this.gUI_InformacionCursos1.devolverInformacion();
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_BotonesCursos1 = new Vista.GUI_BotonesCursos();
        gUI_InformacionCursos1 = new Vista.GUI_InformacionCursos();
        jLabel1 = new javax.swing.JLabel();
        JL_Fondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(816, 423));
        setPreferredSize(new java.awt.Dimension(816, 423));
        setLayout(null);
        add(gUI_BotonesCursos1);
        gUI_BotonesCursos1.setBounds(40, 260, 704, 99);
        add(gUI_InformacionCursos1);
        gUI_InformacionCursos1.setBounds(80, 120, 247, 127);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cursos.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(90, 60, 280, 60);

        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PAntallaCursos.png"))); // NOI18N
        add(JL_Fondo);
        JL_Fondo.setBounds(0, -20, 820, 410);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Fondo;
    private Vista.GUI_BotonesCursos gUI_BotonesCursos1;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
