/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_Registro;
import java.awt.event.ActionEvent;



/**
 *
 * @author SOFIA ELIZONDO
 */
public class GUI_InformacionRegistroCursos extends javax.swing.JFrame{

    /**
     * Creates new form GUI_InformacionCursos
     */
    /**
     * Creates new form ManteniemientoCursos
     */
    Controlador_Registro controlador_Registro;
    public GUI_InformacionRegistroCursos() {
        initComponents();
        setVisible(false);
        this.setLocation(550,225);
       controlador_Registro=new Controlador_Registro(this);
        agregarEventosGUI(controlador_Registro);
       
    }
    
    public void agregarEventosGUI(Controlador_Registro controlador_Registro){
      this.controlador_Registro=controlador_Registro;
      this.JB_RegistroCursos.addActionListener(controlador_Registro);
    }
    
    public String[] devolverInformacionCursos()
    {
        String arreglo[];
        arreglo=new String[3];
        arreglo[0]=this.JT_Siglas.getText();
        arreglo[1]=this.JT_Nombre.getText();
        arreglo[2]=this.JT_Creditos.getText();
  
        return arreglo;
    }
   
    public void blanquear(){
      JT_Siglas.setText("");
      JT_Creditos.setText("");
      JT_Nombre.setText("");
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JB_RegistroCursos = new javax.swing.JButton();
        JT_Creditos = new javax.swing.JTextField();
        JT_Siglas = new javax.swing.JTextField();
        JT_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JL_Nombre = new javax.swing.JLabel();
        JL_Creditos = new javax.swing.JLabel();
        JL_Siglas = new javax.swing.JLabel();
        JL_FondoBlanco = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(595, 308));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Escudo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 40, 314, 215);

        JB_RegistroCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Registrocursos000.png"))); // NOI18N
        JB_RegistroCursos.setActionCommand("RegistroCursos");
        getContentPane().add(JB_RegistroCursos);
        JB_RegistroCursos.setBounds(96, 217, 117, 33);
        getContentPane().add(JT_Creditos);
        JT_Creditos.setBounds(132, 170, 114, 29);
        getContentPane().add(JT_Siglas);
        JT_Siglas.setBounds(132, 139, 112, 25);
        getContentPane().add(JT_Nombre);
        JT_Nombre.setBounds(132, 106, 114, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Registrocursos.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 40, 216, 34);

        JL_Nombre.setText("Nombre");
        getContentPane().add(JL_Nombre);
        JL_Nombre.setBounds(50, 110, 60, 20);

        JL_Creditos.setText("Créditos");
        getContentPane().add(JL_Creditos);
        JL_Creditos.setBounds(50, 170, 50, 20);

        JL_Siglas.setText("Siglas");
        getContentPane().add(JL_Siglas);
        JL_Siglas.setBounds(50, 140, 50, 20);

        JL_FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blanco.png"))); // NOI18N
        getContentPane().add(JL_FondoBlanco);
        JL_FondoBlanco.setBounds(-40, -10, 690, 320);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_RegistroCursos;
    private javax.swing.JLabel JL_Creditos;
    private javax.swing.JLabel JL_FondoBlanco;
    private javax.swing.JLabel JL_Nombre;
    private javax.swing.JLabel JL_Siglas;
    private javax.swing.JTextField JT_Creditos;
    private javax.swing.JTextField JT_Nombre;
    private javax.swing.JTextField JT_Siglas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
